## server
server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    mbeanregistry:
      enabled: on


## management
management:
  info:
    java:
      enabled: on
    os:
      enabled: on
    env:
      enabled: on
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

## spring
spring:
  application:
    name: study-spring-6
  main:
    banner-mode: log


## logging
logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: ${logs_path}/${spring.application.name}.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%-5p} ${PID} --- [%15.15t] %-40.40logger{39} :%06L : %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%-5p} ${PID} --- [%15.15t] %-40.40logger{39} :%06L : %m%n"
  logback:
    rollingpolicy:
      file-name-pattern: "${logs_path}/%d{yyyy-MM-dd}/${spring.application.name}.%d{yyyy-MM-dd}.%i.log"
      max-file-size: 10MB
      max-history: ${log_max_history:10}
  level:
    root: info
    web: info
    org.bobpark: info